import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/checkin.dart';
import '../services/supabase_service.dart';
import '../services/streak_service.dart';
import '../services/badge_service.dart';
import 'auth_provider.dart';
import 'profile_provider.dart';

/// Today's check-ins for current user (multiple per day)
final todayCheckinProvider = FutureProvider<List<Checkin>>((ref) async {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == null) return [];

  final service = ref.watch(supabaseServiceProvider);
  try {
    return await service.getTodayCheckins(userId);
  } catch (e) {
    return [];
  }
});

/// Today's check-in count for current user
final todayCheckinCountProvider = Provider<int>((ref) {
  return ref.watch(todayCheckinProvider).valueOrNull?.length ?? 0;
});

/// This week's check-ins for current user
final weekCheckinsProvider = FutureProvider<List<Checkin>>((ref) async {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == null) return [];

  final service = ref.watch(supabaseServiceProvider);
  try {
    return await service.getWeekCheckins(userId);
  } catch (e) {
    return [];
  }
});

/// Check-ins for a specific month
final monthCheckinsProvider =
    FutureProvider.family<List<Checkin>, DateTime>((ref, month) async {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == null) return [];

  final service = ref.watch(supabaseServiceProvider);
  try {
    final start = DateTime(month.year, month.month, 1);
    final end = DateTime(month.year, month.month + 1, 0);
    return await service.getCheckins(userId, startDate: start, endDate: end);
  } catch (e) {
    return [];
  }
});

/// Semester check-ins (20 weeks = 140 days from semester start)
final semesterCheckinsProvider = FutureProvider<List<Checkin>>((ref) async {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == null) return [];

  final service = ref.watch(supabaseServiceProvider);
  try {
    final now = DateTime.now();
    // Determine semester start: Sep 1 for fall, Mar 1 for spring
    // Pick the most recent semester start that is not in the future
    final currentYear = now.year;
    final fallStart = DateTime(currentYear, 9, 1);
    final springStart = DateTime(currentYear, 3, 1);
    final lastFallStart = DateTime(currentYear - 1, 9, 1);

    DateTime semesterStart;
    if (!fallStart.isAfter(now)) {
      semesterStart = fallStart;
    } else if (!springStart.isAfter(now)) {
      semesterStart = springStart;
    } else {
      semesterStart = lastFallStart;
    }

    final semesterEnd = semesterStart.add(const Duration(days: 140));
    return await service.getCheckins(
      userId,
      startDate: semesterStart,
      endDate: semesterEnd,
    );
  } catch (e) {
    return [];
  }
});

/// Check-in result after submission
class CheckinResult {
  final Checkin checkin;
  final int streak;
  final List<String> newBadges;

  CheckinResult({
    required this.checkin,
    required this.streak,
    required this.newBadges,
  });
}

/// Notifier for check-in actions
final checkinActionsProvider = Provider<CheckinActions>((ref) {
  final service = ref.watch(supabaseServiceProvider);
  return CheckinActions(service, ref);
});

class CheckinActions {
  final SupabaseService _service;
  final Ref _ref;

  CheckinActions(this._service, this._ref);

  /// Submit a new check-in
  Future<CheckinResult> submitCheckin({
    required String studentId,
    required String classroomId,
    required String quadrant,
    required String emotionLabel,
    required String contextTag,
    String? note,
  }) async {
    try {
      // Create the check-in record
      final checkin = Checkin(
        id: '', // Will be generated by Supabase
        studentId: studentId,
        classroomId: classroomId,
        quadrant: quadrant,
        emotionLabel: emotionLabel,
        contextTag: contextTag,
        note: note,
        checkedAt: DateTime.now(),
      );

      final savedCheckin = await _service.createCheckin(checkin);

      // Update streak
      final streakService = StreakService(_service);
      final streak = await streakService.updateStreak(studentId);

      // Check and award badges
      final profile = await _service.getProfile(studentId);
      final badgeService = BadgeService(_service);
      final newBadges = await badgeService.checkAndAwardBadges(
        studentId,
        currentStreak: streak,
        totalCheckins: profile?.totalCheckins ?? 1,
        note: note,
      );

      // Invalidate cached data
      _ref.invalidate(todayCheckinProvider);
      _ref.invalidate(weekCheckinsProvider);
      _ref.invalidate(profileProvider);
      _ref.invalidate(badgesProvider);

      return CheckinResult(
        checkin: savedCheckin,
        streak: streak,
        newBadges: newBadges,
      );
    } catch (e) {
      throw Exception('记录心情失败，请稍后重试');
    }
  }
}
